name: Cron - Post Scheudle

on:
  # "Scheduled workflows run on the latest commit on the default or base branch."
  # — https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
  schedule:
    # Runs “At minute 0, 15, 30, and 45.” (see https://crontab.guru)
    - cron: "* * * * *"
jobs:
  cron-postSchedule:
    env:
      APP_URL: https://app.mysticquill.co
      CRON_API_KEY: ${{ secrets.CRON_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        if: ${{ env.CRON_API_KEY }}
        run: |
          curl https://app.mysticquill.co/api/cron/Post \
            -X POST \
            -H 'content-type: application/json' \
            -H 'authorization: ${{ secrets.CRON_API_KEY }}' \
            --fail
